# permissions for end users to view core5gs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: core5g-viewer-role
rules:
- apiGroups:
  - 5g.5gc.dev
  resources:
  - core5gs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.5gc.dev
  resources:
  - core5gs/status
  verbs:
  - get
